version: "3.8"
services:
  database:
    image: mariadb
    container_name: maria
    environment:
      - MARIADB_ROOT_PASSWORD=ROOT
    ports:
      - "3307:3306"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  spring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/
    depends_on:
      - database
      - redis