version: "3.8"
services:
  database:
    image: mariadb
    container_name: maria
    environment:
      - MARIADB_ROOT_PASSWORD=ROOT
      - MARIADB_DATABASE=gbsw
      - MARIADB_USER=jjoon
      - MARIADB_PASSWORD=1234
      - TZ=ASIA/Seoul

    ports:
      - "3307:3306"

  spring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/
    depends_on:
      - database
      - redis